---
name: rclone

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 1-31/2 * *' # every odd day

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: AnimMouse/setup-rclone@v1
      with:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: ./config/copy.sh >/dev/null
      env:
        NO_DRY_RUN: 1
        LOG_LEVEL: NOTICE
    - run: cat rclone.log
