---
name: onedrive to gphotos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-31/2 * *" # every odd day

jobs:
  copy:
    runs-on: ubuntu-latest
    container: ghcr.io/andreykaipov/rclone-gphotos-fork
    steps:
      - uses: actions/checkout@v4
      - name: onedrive-to-gphotos
        run: |
          rclone version
          printf '%s' "${{ secrets.RCLONE_CONFIG }}" | base64 -d > /tmp/rclone.conf
          rclone --config /tmp/rclone.conf config file
          rclone --config /tmp/rclone.conf listremotes
          ./scripts/onedrive-to-gphotos.sh
