---
name: backup andrey photos

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1-31/2 * *" # every odd day

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: andreykaipov/gphotos-to-onedrive@main
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG_ANDREY }}
          destination_root: /media/albums
